[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.cov]
install_crate = "cargo-kcov"
command = "cargo"
args = ["kcov"]

[tasks.simulate]
dependencies = [
    "format",
    "build",
    "cov"
]